[workspace]
resolver = "3"
members = [
  "examples/doc",
  "microscpi",
  "microscpi-common",
  "microscpi-doc",
  "microscpi-macros",
  "microscpi/fuzz",
]

[workspace.package]
version = "0.6.0"
authors = ["Thomas Gatzweiler <mail@thomasgatzweiler.com>"]
edition = "2024"
homepage = "https://github.com/7h0ma5/microscpi"
repository = "https://github.com/7h0ma5/microscpi"
license = "MIT"

[workspace.dependencies]
microscpi = { path = "microscpi", version = "0.6.0" }
microscpi-common = { path = "microscpi-common", version = "0.6.0" }
microscpi-doc = { path = "microscpi-doc", version = "0.6.0" }
microscpi-macros = { path = "microscpi-macros", version = "0.6.0" }

[workspace.metadata.release]
allow-branch = ["main"]
publish = true
shared-version = true
consolidate-commits = true
tag-name = "v{{version}}"
tag-message = "Release version {{version}}"
